### ISSUE TITLE
bors squash left commit separate from PR/rollup in gh history

### ISSUE THREAD

**Issue by klensy** [rust-lang/homu#182] opened 2022-09-20 14:40 UTC
PR: https://github.com/rust-lang/rust/pull/101806

And now check github history: https://github.com/rust-lang/rust/commits?author=bors for `Sep 20, 2022`, there separate non PR/rollup commit.

`squash` bors command should be disabled: it used rarely, and if used, it sometimes(often?) works not in way as it expected.

**Comment by klensy** [comment] 2022-09-20 14:43
And that PR affected by #181 too.

**Comment by jyn514** [comment] 2022-09-20 14:50
Duplicate of https://github.com/rust-lang/homu/issues/181

**Closed by jyn514** 2022-09-20 14:50 UTC
